name: ci

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2.4.0
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0
      - 
        name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
      -
        name: Login to DockerHub
        uses: docker/login-action@v1.14.0 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Install npm dependencies
        run: npm ci
      - 
        name: cds build
        run: npm run build
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          push: true
#          platforms: linux/amd64,linux/arm/v7,linux/arm64
          tags: gregorwolf/pg-registration:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      -
        name: Build and push Admin UI
        id: docker_build_ui
        uses: docker/build-push-action@v2.7.0
        with:
          context: app
          push: true
          tags: gregorwolf/pg-registration-admin-ui:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      # -
      #   name: Build and push registration UI
      #   id: docker_build_ui
      #   uses: docker/build-push-action@v2.7.0
      #   with:
      #     context: app-registration
      #     push: true
      #     tags: gregorwolf/pg-registration-ui:latest
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}
## Not possible until https://github.com/docker/roadmap/issues/115 is solved
#      - 
#        name: Publish Readme
#        id: publish_readme
#        uses: meeDamian/sync-readme@v1.0.6
#        with:
#          user: ${{ secrets.DOCKERHUB_USERNAME }}
#          pass: ${{ secrets.DOCKERHUB_TOKEN }}
#          slug: gregorwolf/pg-registration
#          readme: ./docker/description.md
#          description: CAP registration using PostgreSQL for persistence